name: Release Package

on:
  push:
    branches:
      - main
      - master
      
permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/build-test
        name: Build & Test

  publish:
    name: Publish release
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        with:
          version: 10.4.1

      - uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          publish: pnpm run release
          version: pnpm bump-version
          commit: 'chore(release): version bump'
          title: 'chore(release): version update'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}